import { v1 as uuidv1 } from "uuid";
import { Invoice, InvoiceStatus } from "../types/invoice";
import {
  createInvoice,
  deleteInvoice,
  getInvoice,
  getUseInvoices,
} from "./invoiceRepository";

const INVOICE_ID = uuidv1();
const INVOICE_USER = "jest@test.com";

test("Create invoice", async () => {
  const invoice: Invoice = {
    id: INVOICE_ID,
    invoicePath: "",
    user: INVOICE_USER,
    status: InvoiceStatus.Created,
    notes: "a note generated by jest",
  };

  const newInvoice = await createInvoice(invoice);

  expect(newInvoice.user).toBe(INVOICE_USER);
  expect(newInvoice.id).toBe(INVOICE_ID);
  expect(newInvoice.createdAt).toBeDefined;
});

test("Get invoice", async () => {
  const invoice = await getInvoice(INVOICE_ID);

  expect(invoice.user).toBe(INVOICE_USER);
  expect(invoice.id).toBe(INVOICE_ID);
});

test("Get invoices by user", async () => {
  const invoices = await getUseInvoices(INVOICE_USER);

  expect(invoices[0].id).toBe(INVOICE_ID);
  expect(invoices.count).toBe(1);
});

test("Get invoices by wrong user", async () => {
  const invoices = await getUseInvoices("bad@user.com");
  expect(invoices.count).toBe(0);
});

test("Delete invoice", async () => {
  await deleteInvoice(INVOICE_ID);
  const invoice = await getInvoice(INVOICE_ID);

  expect(invoice).toBeUndefined();
});
