import { v1 as uuidv1 } from "uuid";
import { Invoice, InvoiceStatus } from "../types/invoice";
import { createInvoice, deleteInvoice, getInvoice } from "./invoiceRepository";

const INVOICE_ID = uuidv1();
const INVOICE_USER = "jest@test.com";

test("Create invoice", async () => {
  const invoice: Invoice = {
    id: INVOICE_ID,
    invoicePath: "",
    user: INVOICE_USER,
    status: InvoiceStatus.Created,
    notes: "a note generated by jest",
  };

  const newInvoice = await createInvoice(invoice);

  expect(newInvoice.user).toBe(INVOICE_USER);
  expect(newInvoice.id).toBe(INVOICE_ID);
  expect(newInvoice.createdAt).toBeDefined;
});

test("Get invoice", async () => {
  const invoice = await getInvoice(INVOICE_ID);

  expect(invoice.user).toBe(INVOICE_USER);
  expect(invoice.id).toBe(INVOICE_ID);
});

test("Delete invoice", async () => {
  await deleteInvoice(INVOICE_ID);
  const invoice = await getInvoice(INVOICE_ID);

  expect(invoice).toBeUndefined();
});
