"use client";
import { SessionProvider } from "next-auth/react";
import RootStyleRegistry from "./components/emotion";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}): JSX.Element {
  return (
    <html lang="en">
      <head></head>
      <body>
        <SessionProvider session={session}>
          <RootStyleRegistry>{children}</RootStyleRegistry>
        </SessionProvider>
      </body>
    </html>
  );
}
