"use client";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";
import RootStyleRegistry from "./components/emotion";
import Loading from "./loading";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}): JSX.Element {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Suspense fallback={<Loading />}>
          <SessionProvider session={session}>
            <RootStyleRegistry>{children}</RootStyleRegistry>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
