import Grid from "../components/Layout/grid";
import Header from "../components/Layout/header";

export const metadata = {
  title: "El famoso dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  session: any;
}): JSX.Element {
  return (
    <>
      <Header />
      <Grid>{children}</Grid>
    </>
  );
}
